---
AWSTemplateFormatVersion: '2010-09-09'
Description: Manages a Single EC2 Instance
Parameters:
  AllocateEIP:
    Type: String
    Default: 'true'
  Ami:
    Type: String
  InstanceName:
    Type: String
  InstanceType:
    Type: String
  KeyName:
    Type: String
  RootVolumeSize:
    Type: String
    Default: 25
  SecurityGroupId:
    Type: String
  SecurityGroupId2:
    Type: String
    Default: 'n/a'
  SubnetId:
    Type: String
  VpcId:
    Type: String
Conditions:
  AddSecondSecurityGroup:
    Fn::Not:
      - Fn::Equals:
        - Ref: SecurityGroupId2
        - 'n/a'
  AllocateEIPAddress:
    Fn::Equals:
      - Ref: AllocateEIP
      - 'true'
Resources:
  Eip:
    Type: AWS::EC2::EIP
    Condition: AllocateEIPAddress
    Properties:
      InstanceId: {Ref: Instance}
      Domain: vpc
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs: {VolumeSize: {Ref: RootVolumeSize}, VolumeType: gp2}
      ImageId: {Ref: Ami}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      Monitoring: true
      SecurityGroupIds:
        - {Ref: SecurityGroupId}
        - Fn::If:
            - AddSecondSecurityGroup
            - Ref: SecurityGroupId2
            - {Ref: 'AWS::NoValue'}
      SubnetId: {Ref: SubnetId}
      UserData:
        Fn::Base64: |
          #cloud-config
          users:
            - name: admin
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
          power_state:
            mode: reboot
      Tags:
        - {Key: Name, Value: {Ref: InstanceName}}
