version: 0.0
os: linux
files:
  - source: /
    destination: /home/admin/ansible_test
permissions:
  - object: /home/admin/ansible_test
    type:
      - directory
    owner: admin
    group: admin
hooks:
  BeforeInstall:
    - location: codedeploy/cleanup.sh
